# Generated by Django 4.0.2 on 2022-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0004_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
