# Generated by Django 4.0.2 on 2022-03-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
